CREATE TABLE ALAT (
  ID_ALAT VARCHAR(255),
  HARGA   DOUBLE PRECISION DEFAULT NULL,
  NAMA    VARCHAR(64) NOT NULL,
  UNIQUE (NAMA),
  PRIMARY KEY (ID_ALAT)
);

CREATE TABLE PESAN (
  ID_PESAN   VARCHAR(255),
  TGL_PESAN  DATE NOT NULL,
  CATATAN    VARCHAR(255) DEFAULT NULL,
  TGL_DATANG DATE NOT NULL,
  TOTAL      DOUBLE PRECISION,
  PRIMARY KEY (ID_PESAN)
);

CREATE TABLE DETAIL_PESAN (
  ID_DETAIL_PESAN CHARACTER VARYING(255),
  ID_ALAT         CHARACTER VARYING(255) NOT NULL,
  ID_PESAN        CHARACTER VARYING(255) NOT NULL,
  JUMLAH          INTEGER                NOT NULL,
  DISKON          DOUBLE PRECISION       NOT NULL,
  PRIMARY KEY (ID_DETAIL_PESAN),
  CONSTRAINT FK_DETAIL_PO1 FOREIGN KEY (ID_ALAT) REFERENCES ALAT (ID_ALAT),
  CONSTRAINT FK_DETAIL_PO2 FOREIGN KEY (ID_PESAN) REFERENCES PESAN (ID_PESAN)
);


